version: "3.9"
services:
    nodejs:
        build:
            context: .
        image: edcelmanuel9/docker-test
        networks:
            - frontend
            - backend
        ports:
            - "3220:3220"
        container_name: moe-nodejs-app
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: Comtechie1998
            MYSQL_DATABASE: cvl
        ports:
            - "3306:3306"
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        container_name: node-mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        depends_on:
            - mysql
        networks:
            - backend
        ports:
            - "3308:80"
        environment:
            - PMA_HOST=node-mysql
            - PMA_PORT=3306
        volumes:
            - /sessions
        container_name: moe-phpmyadmin-app
networks:
    frontend:
    backend:
