version: "3"
services:
    nodejs:
        image: edcelmanuel9/docker-test:1.0
        ports:
            - "3220:3220"
        restart: on-failure
        container_name: cvl
    db:
        image: mysql
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: Comtechie1998
            MYSQL_DATABASE: cvl
            MYSQL_USER: edcelmanuel9
            MYSQL_PASSWORD: Comtechie1998
        ports:
            - 3306:3306
        # command: --init-file /data/application/init.sql --init-file /data/application/cvl.sql
        volumes:
            # - ./init.sql:/data/application/init.sql
            # - ./cvl.sql:/data/application/cvl.sql
            - mysql-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
volumes:
    mysql-data:
