version: "3.1"
services:
    nodejs:
        image: membership:1.0
        ports:
            - "3220:3220"
        restart: on-failure
        container_name: cvl-rest-api
    db:
        image: mysql
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: Comtechie1998
            MYSQL_DATABASE: cvl
            MYSQL_USER: edcelmanuel9
            MYSQL_PASSWORD: Comtechie1998
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql/
            # - ./query:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
